version: 2.1

jobs:
  build:
    machine: true
    resource_class: arm.medium
    steps:
      - checkout
      - run: docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASSWORD"
      - run: |
          VERSION_TAG=$(echo "$CIRCLE_SHA1" | cut -c1-7)
          docker build -t sourabhjagga/openchamber-harden:latest -t sourabhjagga/openchamber-harden:main -t sourabhjagga/openchamber-harden:${VERSION_TAG} .
          docker push sourabhjagga/openchamber-harden:latest
          docker push sourabhjagga/openchamber-harden:main
          docker push sourabhjagga/openchamber-harden:${VERSION_TAG}

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
